# Generated by Django 5.1.2 on 2024-11-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("street_number", models.TextField()),
                ("street_name", models.TextField()),
                ("apt_number", models.TextField()),
                ("zip_code", models.IntegerField()),
                ("dob", models.CharField(max_length=10)),
                ("registration_date", models.CharField(max_length=10)),
                ("party_affiliation", models.TextField()),
                ("precinct_number", models.CharField(max_length=1)),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
            ],
        ),
    ]
