# Generated by Django 5.1.2 on 2024-11-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0003_alter_voter_precinct_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="voter_id",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
