# Generated by Django 5.1.2 on 2024-11-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0004_voter_voter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="voter_id",
            field=models.CharField(max_length=20),
        ),
    ]
