# Generated by Django 5.1.2 on 2024-11-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0005_alter_voter_voter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="apt_number",
            field=models.TextField(blank=True, null=True),
        ),
    ]
