# Generated by Django 5.1.2 on 2024-11-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0006_alter_voter_apt_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(max_length=2),
        ),
    ]
