# Generated by Django 5.1.1 on 2024-10-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.RemoveField(
            model_name="article",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="article",
            name="published",
        ),
        migrations.RemoveField(
            model_name="article",
            name="text",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title",
        ),
    ]
