# Generated by Django 5.1.1 on 2024-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_article_author_article_published_article_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.TextField(default="Unknown Author"),
        ),
    ]
