# Generated by Django 5.1.3 on 2024-11-15 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entertainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_id", models.CharField(max_length=20)),
                ("title", models.TextField()),
                ("cast", models.TextField()),
                ("country", models.TextField()),
                ("date_added", models.TextField()),
                ("release_year", models.IntegerField()),
                ("rating", models.CharField(max_length=6)),
                ("director", models.TextField(blank=True, null=True)),
                ("type", models.TextField()),
                ("duration", models.TextField()),
                ("listed_in", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("address", models.TextField()),
                ("dob", models.DateField()),
                ("email", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anniversary", models.DateTimeField(auto_now=True)),
                (
                    "profile1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile1",
                        to="project.person",
                    ),
                ),
                (
                    "profile2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile2",
                        to="project.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoughts", models.TextField(blank=True)),
                ("rating", models.IntegerField()),
                ("recommend", models.BooleanField()),
                (
                    "entertainment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.entertainment",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.person"
                    ),
                ),
            ],
        ),
    ]
