# Generated by Django 5.1.3 on 2024-12-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="status_message",
            new_name="recommendation",
        ),
    ]
