# Generated by Django 5.1.3 on 2024-12-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_rename_status_message_image_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
