# Generated by Django 5.1.3 on 2024-12-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_recommendation_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="entertainment",
            name="trailer",
            field=models.URLField(blank=True, null=True),
        ),
    ]
