# Generated by Django 5.1.3 on 2024-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entertainment_recommender", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="user",
        ),
        migrations.AddField(
            model_name="entertainment",
            name="description",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entertainment",
            name="duration",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entertainment",
            name="listed_in",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entertainment",
            name="director",
            field=models.TextField(blank=True),
        ),
    ]
