# Generated by Django 5.1.3 on 2024-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "entertainment_recommender",
            "0002_remove_person_user_entertainment_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="entertainment",
            name="director",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.TextField(),
        ),
    ]
