# Generated by Django 5.1.3 on 2024-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "entertainment_recommender",
            "0003_alter_entertainment_director_alter_person_dob",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateField(),
        ),
    ]
