# Generated by Django 5.1.3 on 2024-11-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entertainment_recommender", "0006_person_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendation",
            old_name="user",
            new_name="person",
        ),
    ]
