# Generated by Django 5.1.1 on 2024-10-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0002_statusmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statusmessage",
            name="city",
        ),
    ]
